/**
 * The fluent insert/update/delete builders (spec §4.1, §6).
 *
 * Like the select builder, these assemble immutable data-modification IR and
 * never touch the database until a terminal method (`run`, or `all`/`one`/
 * `maybeOne` on a `RETURNING` query) returns an `Effect`. Shared parameter and
 * selection typing, the selection helpers, and the reusable prepared handle come
 * from {@link module:sql/query-builder-support}.
 *
 * @module sql/mutation-builder
 */
import { Effect, type Option } from "effect"
import { type AnyColumn, columnParamCodec } from "../schema/column.js"
import { type AnyTable, type Insert as InsertInput, type Update as UpdateInput, tableMeta } from "../schema/table.js"
import {
  type ExprNode,
  type InsertConflict,
  type QueryIR,
  type SelectionField,
  type SelectIR,
  queryCapabilityBits,
  snapshotInlineValue,
  nextId
} from "../ir/query-ir.js"
import { capabilityBit, type Capability, bitsToCapabilities, noCapabilities } from "../capabilities/capability.js"
import type { Dialect } from "../dialect.js"
import { PostgresDialect } from "../postgres/dialect.js"
import { ParameterError, type QueryError, type NotFoundError, type TooManyRowsError } from "../errors/index.js"
import { Database } from "../execution/database.js"
import {
  executeCommand,
  executeCompiledCommand,
  executeCompiledMaybeOne,
  executeCompiledOne,
  executeCompiledRows,
  executeMaybeOne,
  executeOne,
  executeRows
} from "../execution/run.js"
import type { CommandResult, CompiledStatement } from "../execution/driver.js"
import { compilableEffect } from "../execution/compiled-query.js"
import {
  type Expr,
  type MergeParameterMaps,
  type Param,
  type ParamsOf,
  isSqlInput,
  toValueNode
} from "./expressions.js"
import {
  argsFrom,
  inspectIr,
  PreparedQuery,
  selectionFrom,
  starSelection,
  type ExactTerminalArguments,
  type MergeParams,
  type NamedParams,
  type SelectFields,
  type SelectResult,
  type TerminalArguments,
  type TerminalCallResult
} from "./query-builder-support.js"

const NO_SELECTION: ReadonlyArray<SelectionField> = Object.freeze([])

type ParameterizedValue<A> = A | Param<string, Exclude<A, undefined>> | Expr<Exclude<A, undefined>>
type ParameterizedInput<T> = { [K in keyof T]: ParameterizedValue<T[K]> }
type InputParams<T> = T extends ReadonlyArray<infer R>
  ? InputParams<R>
  : T extends Record<string, unknown>
    ? MergeParameterMaps<ParamsOf<T[keyof T]>>
    : {}

// --- INSERT ------------------------------------------------------------------

/**
 * Resolves an application key to a writable physical column, rejecting keys that
 * are not own-properties of the table's column map (so `constructor` and other
 * `Object.prototype` keys cannot slip past a truthy lookup — P0.1/Finding 10) and
 * generated columns (which the database computes and cannot be assigned).
 *
 * @param meta - Table metadata.
 * @param key - Application key from insert/update/conflict input.
 * @returns The resolved writable column.
 * @throws {ParameterError} When the key is unknown or targets a generated column.
 */
const resolveWritableColumn = (meta: ReturnType<typeof tableMeta>, key: string): AnyColumn => {
  if (!Object.hasOwn(meta.columns, key)) {
    throw new ParameterError({
      parameter: key,
      reason: "extra",
      message: `Table "${meta.name}" has no column "${key}"`
    })
  }
  const column = meta.columns[key] as AnyColumn
  if (column.def.generated) {
    throw new ParameterError({
      parameter: key,
      reason: "invalid",
      message: `Column "${key}" is generated by the database and cannot be assigned`
    })
  }
  return column
}

/**
 * Projects every insert row into one validated physical-column order.
 *
 * @param table - Target table and writable-column metadata.
 * @param list - Runtime insert rows, including values that may have bypassed TypeScript.
 * @returns Canonical physical columns and expression rows in matching order.
 * @throws {ParameterError} When rows are empty, heterogeneous, unknown, or assign generated columns.
 */
const canonicalizeInsertRows = (
  table: AnyTable,
  list: ReadonlyArray<Record<string, unknown>>
): { columns: string[]; rows: ExprNode[][] } => {
  const meta = tableMeta(table)
  const first = list[0]
  // Empty inserts have no valid SQL representation; fail at construction with a
  // tagged error rather than emitting `INSERT INTO t () VALUES` (P0.6).
  if (!first) {
    throw new ParameterError({
      parameter: "values",
      reason: "missing",
      message: `Insert into "${meta.name}" requires at least one row`
    })
  }
  if (Object.keys(first).length === 0) {
    throw new ParameterError({
      parameter: "values",
      reason: "missing",
      message: `Insert into "${meta.name}" requires at least one column`
    })
  }
  // Canonical application keys, in first-row order, validated against the schema.
  const keys: string[] = []
  const keyColumns: AnyColumn[] = []
  const columns: string[] = []
  for (const key of Object.keys(first)) {
    const column = resolveWritableColumn(meta, key)
    keys.push(key)
    keyColumns.push(column)
    columns.push(column.def.name)
  }
  const keySet = new Set(keys)
  const rows = list.map((row, i) => {
    // Reject keys that are unknown, target a generated column, or appear only in
    // a later row (multi-row inserts must be homogeneous).
    for (const key of Object.keys(row)) {
      if (keySet.has(key)) continue
      resolveWritableColumn(meta, key) // throws for unknown/generated keys
      throw new ParameterError({
        parameter: key,
        reason: "extra",
        message: `Insert row ${i} has extra column "${key}" not present in the first row; multi-row inserts must be homogeneous`
      })
    }
    // Project into canonical order by key; reject rows missing a canonical column.
    return keyColumns.map((column, k) => {
      const key = keys[k] as string
      if (!Object.hasOwn(row, key)) {
        throw new ParameterError({
          parameter: key,
          reason: "missing",
          message: `Insert row ${i} is missing column "${key}" present in the first row; multi-row inserts must be homogeneous`
        })
      }
      return inputValueNode(meta.name, column, row[key])
    })
  })
  return { columns, rows }
}

/**
 * Converts a mutation input to either a named expression or an inline-bound parameter.
 *
 * @param table - Physical table name used for inline parameter diagnostics.
 * @param column - Target schema column and codec.
 * @param value - Application value, named parameter, or expression.
 * @returns Runtime expression used by insert and update IR.
 */
const inputValueNode = (table: string, column: AnyColumn, value: unknown): ExprNode => {
  // Only branded Thor constructs (param(), excluded(), scalar(), …) carry SQL
  // semantics. Look-alike application data — e.g. JSON containing a `node` key
  // or `_tag: "Param"` — is always bound as an encoded parameter instead.
  if (isSqlInput(value)) return toValueNode(value, column)
  return {
    _tag: "Param",
    name: `${table}.${column.def.name}`,
    codec: columnParamCodec(column),
    value: snapshotInlineValue(value)
  }
}

/**
 * Converts application update input into physical assignments.
 *
 * @param table - Target table.
 * @param input - Application-keyed update values.
 * @returns Ordered physical assignments.
 */
const assignmentsFrom = (
  table: AnyTable,
  input: Record<string, unknown>
): ReadonlyArray<{ readonly column: string; readonly value: ExprNode }> => {
  const meta = tableMeta(table)
  // Reject unknown/generated keys rather than silently dropping them — a typo
  // must not become a partial update or an empty `SET` (Finding 8/10).
  return Object.entries(input).map(([key, value]) => {
    const column = resolveWritableColumn(meta, key)
    return { column: column.def.name, value: inputValueNode(meta.name, column, value) }
  })
}

/** @stable Insert, update, or delete query with a decoded `RETURNING` selection. */
export class ReturningQuery<A, P extends NamedParams = {}> {
  /**
   * @param ir - Data-modification representation containing `RETURNING`.
   * @param fields - Runtime fields used to decode returned rows.
   */
  constructor(
    readonly ir: Exclude<QueryIR, SelectIR>,
    private readonly fields: SelectionField[]
  ) {}

  /**
   * @experimental Debugging shape only.
   * @returns Stable query-shape metadata without compiling or executing.
   */
  inspect() {
    return inspectIr(this.ir)
  }

  /**
   * @param dialect - Target SQL dialect; defaults to PostgreSQL.
   * @returns Compiled query data.
   */
  toSql(dialect: Dialect = PostgresDialect): CompiledStatement {
    return dialect.compileQuery(this.ir)
  }

  /**
   * @returns Capabilities required to execute this returning query.
   */
  requiredCapabilities(): ReadonlyArray<Capability> {
    return bitsToCapabilities(queryCapabilityBits(this.ir))
  }

  /**
   * @stable
   * @typeParam Args - Omitted for compilation or no-param execution; otherwise named values.
   * @param args - Named parameter values.
   * @returns An Effect yielding every returned row.
   */
  all<Args extends TerminalArguments<P>>(
    ...args: Args & ExactTerminalArguments<P, Args>
  ): TerminalCallResult<P, ReadonlyArray<A>, QueryError, "all", Args> {
    const effect = Effect.flatMap(Database, (db) => executeRows<A>(this.ir, this.fields, db, argsFrom(args)))
    return compilableEffect(effect, this.ir, this.fields, "all", executeCompiledRows<A>) as TerminalCallResult<
      P,
      ReadonlyArray<A>,
      QueryError,
      "all",
      Args
    >
  }

  /**
   * @stable
   * @typeParam Args - Omitted for compilation or no-param execution; otherwise named values.
   * @param args - Named parameter values.
   * @returns An Effect yielding exactly one returned row.
   * @throws {NotFoundError} Through the Effect error channel when no row is returned.
   * @throws {TooManyRowsError} Through the Effect error channel when multiple rows are returned.
   */
  one<Args extends TerminalArguments<P>>(
    ...args: Args & ExactTerminalArguments<P, Args>
  ): TerminalCallResult<P, A, QueryError | NotFoundError | TooManyRowsError, "one", Args> {
    const operation = `${this.ir._tag}.one`
    const effect = Effect.flatMap(Database, (db) => executeOne<A>(this.ir, this.fields, db, argsFrom(args), operation))
    return compilableEffect(effect, this.ir, this.fields, "one", (plan, statement, service, values) =>
      executeCompiledOne<A>(plan, statement, service, values, operation)
    ) as TerminalCallResult<P, A, QueryError | NotFoundError | TooManyRowsError, "one", Args>
  }

  /**
   * @stable
   * @typeParam Args - Omitted for compilation or no-param execution; otherwise named values.
   * @param args - Named parameter values.
   * @returns An Effect yielding zero or one returned row.
   * @throws {TooManyRowsError} Through the Effect error channel when multiple rows are returned.
   */
  maybeOne<Args extends TerminalArguments<P>>(
    ...args: Args & ExactTerminalArguments<P, Args>
  ): TerminalCallResult<P, Option.Option<A>, QueryError | TooManyRowsError, "maybeOne", Args> {
    const operation = `${this.ir._tag}.maybeOne`
    const effect = Effect.flatMap(Database, (db) =>
      executeMaybeOne<A>(this.ir, this.fields, db, argsFrom(args), operation)
    )
    return compilableEffect(effect, this.ir, this.fields, "maybeOne", (plan, statement, service, values) =>
      executeCompiledMaybeOne<A>(plan, statement, service, values, operation)
    ) as TerminalCallResult<P, Option.Option<A>, QueryError | TooManyRowsError, "maybeOne", Args>
  }

  /**
   * @stable
   * @typeParam Args - Omitted for compilation or no-param execution; otherwise named values.
   * @param args - Named parameter values.
   * @returns An Effect yielding the affected-row count.
   */
  run<Args extends TerminalArguments<P>>(
    ...args: Args & ExactTerminalArguments<P, Args>
  ): TerminalCallResult<P, CommandResult, QueryError, "run", Args> {
    const effect = Effect.flatMap(Database, (db) => executeCommand(this.ir, db, argsFrom(args)))
    return compilableEffect(effect, this.ir, this.fields, "run", executeCompiledCommand) as TerminalCallResult<
      P,
      CommandResult,
      QueryError,
      "run",
      Args
    >
  }

  /**
   * Freeze this returning mutation into a reusable precompiled handle (spec §15.15).
   *
   * @experimental Prefer terminal `.compile()` for the v1 stable API.
   * @param name - Stable handle name (defaults to a generated id).
   * @returns A `PreparedQuery` exposing `all`/`one`/`maybeOne`/`run`.
   */
  prepare(name?: string): PreparedQuery<A, P> {
    return new PreparedQuery<A, P>(name ?? nextId("prepared"), this.ir, this.fields)
  }
}

/**
 * Resolves an explicit `RETURNING` selection or the table's star selection.
 *
 * @param table - Target table.
 * @param fields - Optional explicit return fields.
 * @returns Runtime selection metadata.
 */
const returningFields = (table: AnyTable, fields?: SelectFields): SelectionField[] =>
  fields ? selectionFrom(fields) : starSelection(table)

/** @stable Begins an `INSERT` for a table; call `values()` to supply rows. */
export class InsertBuilder<T extends AnyTable> {
  /**
   * @param table - Target table.
   */
  constructor(private readonly table: T) {}

  /**
   * Adds one or more rows to an insert.
   *
   * @param input - A single insert value or homogeneous array of values.
   * @returns An insert builder ready for `returning()` or `run()`.
   */
  values<I extends ParameterizedInput<InsertInput<T>> | ReadonlyArray<ParameterizedInput<InsertInput<T>>>>(
    input: I
  ): InsertValues<T, InputParams<I>> {
    const list = (Array.isArray(input) ? input : [input]) as ReadonlyArray<Record<string, unknown>>
    const { columns, rows } = canonicalizeInsertRows(this.table, list)
    return new InsertValues<T, InputParams<I>>(this.table, columns, rows)
  }
}

/** @stable A populated `INSERT` awaiting `returning()`, conflict policy, or `run()`. */
export class InsertValues<T extends AnyTable, P extends NamedParams = {}> {
  /**
   * @param table - Target table.
   * @param columns - Physical columns included by the insert.
   * @param rows - Parameter expressions for every inserted row.
   * @param conflict - Optional dialect-specific conflict policy.
   */
  constructor(
    private readonly table: T,
    private readonly columns: string[],
    private readonly rows: ExprNode[][],
    private readonly conflict?: InsertConflict
  ) {}

  /**
   * @param returning - Optional returned-field metadata.
   * @returns Insert runtime representation.
   */
  private ir(returning?: SelectionField[]): Exclude<QueryIR, SelectIR> {
    const meta = tableMeta(this.table)
    return {
      _tag: "Insert",
      id: nextId("Insert"),
      into: { name: meta.name },
      columns: this.columns,
      rows: this.rows,
      ...(this.conflict ? { conflict: this.conflict } : {}),
      ...(returning ? { returning } : {}),
      capabilities:
        (returning ? capabilityBit("insert.returning") : noCapabilities) |
        (this.conflict?.kind === "onConflict" ? capabilityBit("insert.onConflict") : noCapabilities) |
        (this.conflict?.kind === "onDuplicateKey" ? capabilityBit("insert.onDuplicateKey") : noCapabilities),
      cardinality: this.rows.length === 1 ? "one" : "many",
      annotations: { tableNames: [meta.name], idempotency: "non-idempotent" }
    }
  }

  /** @experimental Debugging shape only. @returns Stable insert-shape metadata without executing. */
  inspect() {
    return inspectIr(this.ir())
  }

  /**
   * @param dialect - Target SQL dialect; defaults to PostgreSQL.
   * @returns Compiled insert SQL and parameter metadata.
   */
  toSql(dialect: Dialect = PostgresDialect): CompiledStatement {
    return dialect.compileQuery(this.ir())
  }

  /** @returns Capabilities required by this insert. */
  requiredCapabilities(): ReadonlyArray<Capability> {
    return bitsToCapabilities(queryCapabilityBits(this.ir()))
  }

  /**
   * Adds a PostgreSQL/SQLite-style `ON CONFLICT DO NOTHING` policy.
   *
   * @param target - Optional conflict-target columns.
   * @returns A new insert builder guarded by `insert.onConflict`.
   */
  onConflictDoNothing(target: ReadonlyArray<AnyColumn> = []): InsertValues<T, P> {
    return new InsertValues<T, P>(this.table, this.columns, this.rows, {
      kind: "onConflict",
      target: target.map((column) => column.def.name),
      action: "nothing",
      set: []
    })
  }

  /**
   * Adds a PostgreSQL/SQLite-style `ON CONFLICT DO UPDATE` policy.
   *
   * @param target - Conflict-target columns.
   * @param input - Assignments applied to the conflicting row.
   * @returns A new insert builder guarded by `insert.onConflict`.
   */
  onConflictDoUpdate<I extends ParameterizedInput<UpdateInput<T>>>(
    target: ReadonlyArray<AnyColumn>,
    input: I
  ): InsertValues<T, MergeParams<P, InputParams<I>>> {
    return new InsertValues<T, MergeParams<P, InputParams<I>>>(this.table, this.columns, this.rows, {
      kind: "onConflict",
      target: target.map((column) => column.def.name),
      action: "update",
      set: assignmentsFrom(this.table, input as Record<string, unknown>)
    })
  }

  /**
   * Adds a MySQL-style `ON DUPLICATE KEY UPDATE` policy.
   *
   * @param input - Assignments applied to the conflicting row.
   * @returns A new insert builder guarded by `insert.onDuplicateKey`.
   */
  onDuplicateKeyUpdate<I extends ParameterizedInput<UpdateInput<T>>>(
    input: I
  ): InsertValues<T, MergeParams<P, InputParams<I>>> {
    return new InsertValues<T, MergeParams<P, InputParams<I>>>(this.table, this.columns, this.rows, {
      kind: "onDuplicateKey",
      set: assignmentsFrom(this.table, input as Record<string, unknown>)
    })
  }

  /**
   * Adds a `RETURNING` clause.
   *
   * @param fields - Optional selected fields; omit to return every table column.
   * @returns A row-returning query guarded by dialect capabilities.
   */
  returning<F extends SelectFields>(
    fields?: F
  ): ReturningQuery<F extends SelectFields ? SelectResult<F> : Record<string, unknown>, P> {
    const selection = returningFields(this.table, fields)
    return new ReturningQuery(this.ir(selection), selection)
  }

  /**
   * @stable
   * @typeParam Args - Omitted for compilation or no-param execution; otherwise named values.
   * @param args - Named parameter values.
   * @returns An Effect yielding the affected-row count.
   */
  run<Args extends TerminalArguments<P>>(
    ...args: Args & ExactTerminalArguments<P, Args>
  ): TerminalCallResult<P, CommandResult, QueryError, "run", Args> {
    const ir = this.ir()
    const effect = Effect.flatMap(Database, (db) => executeCommand(ir, db, argsFrom(args)))
    return compilableEffect(effect, ir, NO_SELECTION, "run", executeCompiledCommand) as TerminalCallResult<
      P,
      CommandResult,
      QueryError,
      "run",
      Args
    >
  }
}

// --- UPDATE ------------------------------------------------------------------

/** @stable Begins an `UPDATE` for a table; call `set()` to supply assignments. */
export class UpdateBuilder<T extends AnyTable> {
  /**
   * @param table - Target table.
   */
  constructor(private readonly table: T) {}

  /**
   * @param input - Partial non-generated column values.
   * @returns An update builder with assignments.
   */
  set<I extends ParameterizedInput<UpdateInput<T>>>(input: I): UpdateValues<T, InputParams<I>> {
    return new UpdateValues<T, InputParams<I>>(
      this.table,
      assignmentsFrom(this.table, input as Record<string, unknown>)
    )
  }
}

/** @stable A populated `UPDATE` awaiting `where()`, `returning()`, or `run()`. */
export class UpdateValues<T extends AnyTable, P extends NamedParams = {}> {
  private whereNode?: ExprNode

  /**
   * @param table - Target table.
   * @param assignments - Physical column assignments.
   * @param whereNode - Optional predicate retained by an immutable clone.
   */
  constructor(
    private readonly table: T,
    private readonly assignments: ReadonlyArray<{ column: string; value: ExprNode }>,
    whereNode?: ExprNode
  ) {
    if (whereNode !== undefined) this.whereNode = whereNode
  }

  /**
   * @param predicate - Predicate replacing the current `WHERE` clause.
   * @returns This update builder.
   */
  where<E extends ExprNode>(predicate: E): UpdateValues<T, MergeParams<P, ParamsOf<E>>> {
    return new UpdateValues<T, MergeParams<P, ParamsOf<E>>>(this.table, this.assignments, predicate)
  }

  /**
   * @param returning - Optional returned-field metadata.
   * @returns Update runtime representation.
   */
  private ir(returning?: SelectionField[]): Exclude<QueryIR, SelectIR> {
    const meta = tableMeta(this.table)
    return {
      _tag: "Update",
      id: nextId("Update"),
      table: { name: meta.name },
      set: this.assignments,
      ...(this.whereNode ? { where: this.whereNode } : {}),
      ...(returning ? { returning } : {}),
      capabilities: returning ? capabilityBit("update.returning") : noCapabilities,
      cardinality: "many",
      annotations: { tableNames: [meta.name], idempotency: "unknown" }
    }
  }

  /** @experimental Debugging shape only. @returns Stable update-shape metadata without executing. */
  inspect() {
    return inspectIr(this.ir())
  }

  /**
   * @param dialect - Target SQL dialect; defaults to PostgreSQL.
   * @returns Compiled update SQL and parameter metadata.
   */
  toSql(dialect: Dialect = PostgresDialect): CompiledStatement {
    return dialect.compileQuery(this.ir())
  }

  /** @returns Capabilities required by this update. */
  requiredCapabilities(): ReadonlyArray<Capability> {
    return bitsToCapabilities(queryCapabilityBits(this.ir()))
  }

  /**
   * @param fields - Optional fields to return; omit for all columns.
   * @returns A row-returning update query.
   */
  returning<F extends SelectFields>(
    fields?: F
  ): ReturningQuery<F extends SelectFields ? SelectResult<F> : Record<string, unknown>, P> {
    const selection = returningFields(this.table, fields)
    return new ReturningQuery(this.ir(selection), selection)
  }

  /**
   * @stable
   * @typeParam Args - Omitted for compilation or no-param execution; otherwise named values.
   * @param args - Named parameter values.
   * @returns An Effect yielding the affected-row count.
   */
  run<Args extends TerminalArguments<P>>(
    ...args: Args & ExactTerminalArguments<P, Args>
  ): TerminalCallResult<P, CommandResult, QueryError, "run", Args> {
    const ir = this.ir()
    const effect = Effect.flatMap(Database, (db) => executeCommand(ir, db, argsFrom(args)))
    return compilableEffect(effect, ir, NO_SELECTION, "run", executeCompiledCommand) as TerminalCallResult<
      P,
      CommandResult,
      QueryError,
      "run",
      Args
    >
  }
}

// --- DELETE ------------------------------------------------------------------

/** @stable A `DELETE` for a table awaiting `where()`, `returning()`, or `run()`. */
export class DeleteBuilder<T extends AnyTable, P extends NamedParams = {}> {
  private whereNode?: ExprNode

  /**
   * @param table - Target table.
   * @param whereNode - Optional predicate retained by an immutable clone.
   */
  constructor(
    private readonly table: T,
    whereNode?: ExprNode
  ) {
    if (whereNode !== undefined) this.whereNode = whereNode
  }

  /**
   * @param predicate - Predicate replacing the current `WHERE` clause.
   * @returns This delete builder.
   */
  where<E extends ExprNode>(predicate: E): DeleteBuilder<T, MergeParams<P, ParamsOf<E>>> {
    return new DeleteBuilder<T, MergeParams<P, ParamsOf<E>>>(this.table, predicate)
  }

  /**
   * @param returning - Optional returned-field metadata.
   * @returns Delete runtime representation.
   */
  private ir(returning?: SelectionField[]): Exclude<QueryIR, SelectIR> {
    const meta = tableMeta(this.table)
    return {
      _tag: "Delete",
      id: nextId("Delete"),
      from: { name: meta.name },
      ...(this.whereNode ? { where: this.whereNode } : {}),
      ...(returning ? { returning } : {}),
      capabilities: returning ? capabilityBit("delete.returning") : noCapabilities,
      cardinality: "many",
      annotations: { tableNames: [meta.name], idempotency: "idempotent" }
    }
  }

  /** @experimental Debugging shape only. @returns Stable delete-shape metadata without executing. */
  inspect() {
    return inspectIr(this.ir())
  }

  /**
   * @param dialect - Target SQL dialect; defaults to PostgreSQL.
   * @returns Compiled delete SQL and parameter metadata.
   */
  toSql(dialect: Dialect = PostgresDialect): CompiledStatement {
    return dialect.compileQuery(this.ir())
  }

  /** @returns Capabilities required by this delete. */
  requiredCapabilities(): ReadonlyArray<Capability> {
    return bitsToCapabilities(queryCapabilityBits(this.ir()))
  }

  /**
   * @param fields - Optional fields to return; omit for all columns.
   * @returns A row-returning delete query.
   */
  returning<F extends SelectFields>(
    fields?: F
  ): ReturningQuery<F extends SelectFields ? SelectResult<F> : Record<string, unknown>, P> {
    const selection = returningFields(this.table, fields)
    return new ReturningQuery(this.ir(selection), selection)
  }

  /**
   * @stable
   * @typeParam Args - Omitted for compilation or no-param execution; otherwise named values.
   * @param args - Named parameter values.
   * @returns An Effect yielding the affected-row count.
   */
  run<Args extends TerminalArguments<P>>(
    ...args: Args & ExactTerminalArguments<P, Args>
  ): TerminalCallResult<P, CommandResult, QueryError, "run", Args> {
    const ir = this.ir()
    const effect = Effect.flatMap(Database, (db) => executeCommand(ir, db, argsFrom(args)))
    return compilableEffect(effect, ir, NO_SELECTION, "run", executeCompiledCommand) as TerminalCallResult<
      P,
      CommandResult,
      QueryError,
      "run",
      Args
    >
  }
}
